### ISSUE TITLE
Actually!

### ISSUE THREAD

**Issue by jevgenyonegin** [stryker-project/swb#1]
It's not really brute force, it is dictionary attack! It's cool that you wrote it as bash, but there is no future progress... lots of routers doesn't recognise access every 3-5 seconds. Handshake - nothing can be better. And yes, I am again this guy, who told you to not make this futures for everyone... Keep people learning and geting learning, do not make them one-click persons, finally they will hack you, in one click.

**Comment by zalexdev** [comment]
So, about speed - on tested device (POCO X3 NFC, AOSP, A11). It's enough 0.5s in 97% of attempts. But some of MIUI or etc. based ROMs can have a different value, that's why we have an option user to adjust this value by themselves.
About brute force, basically you're right, i will change it later. But in some way, it is bruting, using wordlist so..
About handshake, of course you're right here too, but it is for smartphones that doesn't have a parched kernel, or person doesn't have an adapter, basically better then nothing 
About the one click solutions. Basically, whole this project was made, because if more people can test themselves for a basic exploit, it will be much secure, then they will "ohh, it's too hard to learn", who wants to learn — will. Who always wanted a one click solution, will found it in any way. And it is a pentest project, not hacking, big difference
For comments or discussing like this, u better use our telegram chat, or our support email, GitHub issues not for this type of conversations
Thanks!,
